### ISSUE TITLE
[Feature request] Include a hibernate option

### ISSUE THREAD

**Issue by vtenfys** [system76/gnome-shell-extension-suspend-button#3]
It would be nice to have the ability to have a hibernate button in the system menu in addition to sleep. Previously I was using [this extension](https://extensions.gnome.org/extension/755/hibernate-status-button/) but as of Gnome 3.32, this has stopped working.

I would propose adding a checkbox in the settings dialog to enable/disable the hibernate button, which could be hidden by default, since Pop doesn't work with hibernation OOTB. Then, the "Suspend default" option could be changed to "Default button" as a dropdown.

**Comment by jackpot51** [comment]
We will not be adding this feature. I recommend following this bug: https://github.com/arelange/gnome-shell-extension-hibernate-status/issues/25

**Comment by gagan0123** [comment]
Seems that issue has been patched, should we reopen this one?
I need hibernate option as, there usually are a lot of things I'm working on, and suspend simply isn't an option when going somewhere distant. So I would like to have the option to hibernate, rather than shut down or suspend my laptop during long travels.

**Comment by ndoritos** [comment]
I have the exact same need.  Will this become an option in a future update/release?  Thank you

**Comment by farzadpanahi** [comment]
Any update on this? The referenced blocking issue above has been fixed. Why can't we have hibernate in pop os?

**Comment by linuxtopia** [comment]
Still no answer?

**Comment by king-shak** [comment]
@jackpot51 why not?

I dual boot between Windows 10 and PopOS, and one of the nice things about how Windows hibernates is that the system fully shuts down. This way I can go over to PopOS, and when I'm done with it, I can go back right back to where I was in Windows, which is far more convenient than having to set up all my applications every time. I can't do this with PopOS because it still keeps stuff in memory and doesn't fully shut down. I don't want to DIY it either (I know there are guides out there) in case I break something, and I'm, sure many others feel the same.

I understand my use case may be a minority, but what is the rationale for not implementing this?
